ARG CROSS_BASE_IMAGE
FROM $CROSS_BASE_IMAGE

ARG CROSS_DEB_ARCH

RUN dpkg --add-architecture $CROSS_DEB_ARCH && apt-get update
RUN apt-get install --assume-yes libusb-1.0-0:armhf libusb-1.0-0-dev:$CROSS_DEB_ARCH

#RUN find / -name '*.so' && exit 1
